[phases.setup]
nixPkgs = ["...", "automake", "build-essential", "pkg-config", "libtool", "libffi-dev", "libssl-dev", "libgmp-dev", "python3-dev"]
[phases.install]
cmds = ["bundle install"]
[phases.build]
cmds = []
[phases.release]
cmds = ["rails db:create", "rails db:migrate"]
