[phases.setup]
nixPkgs = ["...", "automake", "libffi-dev","libgmp-dev", "libssl-dev"]
[phases.install]
cmds = ["bundle install"]
[phases.build]
cmds = []
[phases.release]
cmds = ["rails db:create", "rails db:migrate"]
